version: "3"
services:
  solace:
    image: solace/solace-pubsub-standard
    volumes:
      - solace-data:/usr/sw
    ports:
      - 2222:2222
      - 8080:8080
      - 55555:55555
      - 9000:9000
    shm_size: 2g
    environment:
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin

volumes:
  solace-data:
